baseurl = "https://practicalreason.net"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Reverting to Type"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
googleAnalytics = "UA-35024589-1"

[Params]
  # homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  #subtitle = "Extrapolating from experience to form generalisations"
  mainSections = ["post","posts"]
  # logo = "img/avatar-icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  # rss = true
  comments = false
  readingTime = false
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = false
  showRelatedPosts = true
  hideAuthor = true
  gcse = "016589942105066015434:5zcne19zyy5" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[[Params.bigimg]]
  src = "/img/wall.jpg"
[[Params.bigimg]]
  src = "/img/brick.jpg" 
[[Params.bigimg]]
  src = "/img/wall-wild-flowers.jpg"
  position = "center top"
[[Params.bigimg]]
  src = "/img/triangle.jpg"
  # desc = "Triangle"
[[Params.bigimg]]
  src = "/img/sphere.jpg"
  # desc = "Sphere"
  # position: see values of CSS background-position.
  position = "center top"
[[Params.bigimg]]
  src = "/img/hexagon.jpg"
  # desc = "Hexagon"

[Author]
  name = "Dermot O'Halloran"
  #website = "yourwebsite.com"
  email = "dermot@practicalreason.net"
  twitter = "dohalloran"
  #facebook = "username"
  github = "djohalloran"
  #gitlab = "username"
  #bitbucket = "username"  
  #reddit = "username"
  #linkedin = "username"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"
  #500px = "username"
  #codepen = "username"
  #mastodon = "url"
  #kaggle = "username"
  #weibo = "username"
  #slack = "username"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 3
	
[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 3
	

#[[menu.main]]
#    identifier = "samples"
#    name = "Samples"
#    weight = 2

#[[menu.main]]
#    parent = "samples"
#    name = "Big Image Sample"
#    url = "post/2017-03-07-bigimg-sample"
#    weight = 1

#[[menu.main]]
#    parent = "samples"
#    name = "Math Sample"
#    url = "post/2017-03-05-math-sample"
#    weight = 2

#[[menu.main]]
#    parent = "samples"
#    name = "Code Sample"
#    url = "post/2016-03-08-code-sample"
#    weight = 3


